- hosts: storage
  become: yes
  gather_facts: false
  tasks:
  - name: Install targetcli
    yum:
      name: targetcli
      state: latest
  - name: Create block device
    shell: sudo targetcli /backstores/block create disk01 /dev/vdb
  - name: Create iqn
    shell: sudo targetcli /iscsi create iqn.ivan-23.ru.otus:storage.target00
  - name: Create LUN 0
    shell: sudo targetcli /iscsi/iqn.ivan-23.ru.otus:storage.target00/tpg1/luns create /backstores/block/disk01

- hosts: cluster
  become: yes
  gather_facts: false
  tasks:
  - name: Set initiator
    shell: sudo iscsiadm -m discovery -t st -p 51.250.94.24
  - name: Set node
    shell: sudo iscsiadm -m node
  - name: Enable iscsi
    shell: sudo systemctl enable iscsi --now
  - name: Add Initiator Name to Targets ACL
    command: cat /etc/iscsi/initiatorname.iscsi
    register: var_initiatorname
  - name: Grant access
    command: "sudo targetcli /iscsi/iqn.ivan-23.ru.otus:storage.target00/tpg1/acls create {{ var_initiatorname.stdout.split('InitiatorName=').1 }}"
    delegate_to: "{{ storage_ip }}"
  - name: Login Initiartor
    shell: sudo iscsiadm -m node -l -T iqn.ivan-23.ru.otus:storage.target00
  - name: Enable MultiPath
    shell: sudo mpathconf --enable --with_multipathd y
  - name: Add MultiPath
    shell: sudo multipath -a /dev/sda | cut -d "'" -f 2
    register: var_wwid 
  - debug:
      msg: "{{var_wwid.stdout}}"
  - name: Editing multipath.conf
    lineinfile: dest=/etc/multipath.conf regexp='^blacklist {' line='#blacklist {'
  - lineinfile: dest=/etc/multipath.conf regexp='^}' line='#}'
  - lineinfile: dest=/etc/multipath.conf line="multipaths {"
  - lineinfile: dest=/etc/multipath.conf line="  multipath {"
  - lineinfile: dest=/etc/multipath.conf line="    wwid {{var_wwid.stdout}}"
  - lineinfile: dest=/etc/multipath.conf line="    alias otusDisk"
  - lineinfile: dest=/etc/multipath.conf line="  }"
  - lineinfile: dest=/etc/multipath.conf line="}"
  - name: Restart MultiPath
    service: 
      name: multipathd
      state: restarted
  - block:
    - name: Disable stonith
      shell: sudo pcs property set stonith-enabled=false
    - name: No quorum policy freeze
      shell: sudo pcs property set no-quorum-policy=freeze
    - name: Create DLM pacemaker resource
      shell: sudo pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    - name: Create CLVM pacemaker resource
      shell: sudo pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true
    - name: Set order constraint
      shell: sudo pcs constraint order start dlm-clone then clvmd-clone
    - name: Pvcreate
      shell: sudo pvcreate /dev/mapper/otusDisk
      retries: 10
      delay: 5
      register: result
      until: result.rc == 0
    - name: Vgrecate
      shell: sudo vgcreate -Ay -cy cluster_vg /dev/mapper/otusDisk
      retries: 10
      delay: 5
      register: result
      until: result.rc == 0
    - name: Lvcreate
      shell: sudo lvcreate -L900M -n cluster_lv cluster_vg
    - name: Creating FS
      shell: sudo mkfs.gfs2 -O -j4 -p lock_dlm -t mycluster:gfs2 /dev/cluster_vg/cluster_lv
    - name: Mount FS
      shell: sudo pcs resource create clusterfs Filesystem device="/dev/cluster_vg/cluster_lv" directory="/mnt/gfs2" fstype="gfs2" options=noatime op monitor interval=10s on-fail=ignore clone interleave=true
    when: ansible_hostname == "node-0"
