    - name: Download Filebeat's Debian package
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.10.0-amd64.deb"
        dest: "/tmp/filebeat.deb"

    - name: Install Filebeat
      apt:
        deb: "/tmp/filebeat.deb"

    - name: Drop in filebeat.yml
      template:
        src: "templates/filebeat.yml.j2"
        dest: "/etc/filebeat/filebeat.yml"
        owner: root
        group: root
        mode: '0644'

    - name: Enable and Configure the Filebeat service
      systemd:
        name: filebeat
        enabled: yes
        state: restarted
        daemon_reload: yes

    - name: Setup Filebeat
      command: filebeat setup -e
      args:
        chdir: "/usr/share/filebeat"
