
# Consul Installation and Setup Playbook
# This playbook outlines the steps to install and configure Consul on a Linux system.

## Step 1: Install Consul
- hosts: all
  become: yes
  tasks:
    - name: Download Consul
      get_url:
        url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
        dest: "/tmp/consul.zip"
    
    - name: Unzip Consul
      unarchive:
        src: "/tmp/consul.zip"
        dest: "/usr/local/bin"
        remote_src: yes
    
    - name: Create Consul user
      user:
        name: consul
        system: yes
        home: /etc/consul.d
        shell: /bin/false
    
    - name: Create directories for Consul
      file:
        path: "{{ item }}"
        state: directory
        owner: consul
        group: consul
      loop:
        - /opt/consul
        - /etc/consul.d

## Step 2: Configure Consul
    - name: Create Consul configuration file
      copy:
        dest: "/etc/consul.d/consul.hcl"
        content: |
          {
            "server": true,
            "node_name": "consul-server-1",
            "data_dir": "/opt/consul",
            "bind_addr": "{{ bind_ip }}",
            "client_addr": "0.0.0.0",
            "bootstrap_expect": 3,
            "ui": true,
            "retry_join": [{{ server_ips }}]
          }
        owner: consul
        group: consul

## Step 3: Start Consul
    - name: Start Consul
      shell: "consul agent -config-dir=/etc/consul.d"
      async: 100
      poll: 0
      become: yes
      become_user: consul
