- name: Install Nginx
  yum:
    name: nginx
    state: present

#- name: Copy Nginx configuration file
#  copy:
#     src: nginx.conf
#     dest: /etc/nginx/nginx.conf
#     mode: '0644'
#   notify: Restart Nginx

- name: Start Nginx
  systemd:
    name: nginx
    state: started
    enabled: true