---
- name: Setup Ceph Cluster Configurations
  hosts: ceph_nodes
  become: yes
  tasks:

#    - name: Generate FSID
#      local_action: command python3 generate_fsid.py
#      register: fsid_result

#    - name: Copy configuration template to nodes
#      template:
#        src: ceph.conf.j2
#        dest: /etc/ceph/ceph.conf

#    - name: Ensure directories exist for Ceph
#      file:
#        path: /etc/ceph
#        state: directory
#        owner: root

#    - name: Copy ceph.conf to nodes
#      copy:
#        src: /etc/ceph/ceph.conf
#        dest: /etc/ceph/ceph.conf
#        owner: root
#        mode: "0644"


    - name: Generate admin keyring
      command: >
        ceph-authtool --create-keyring /etc/ceph/ceph.client.admin.keyring
        --gen-key -n client.admin
        --cap mon 'allow *'
        --cap osd 'allow *'
        --cap mds 'allow *'

    - name: Copy keyring to nodes
      copy:
        src: /etc/ceph/ceph.client.admin.keyring
        dest: /etc/ceph/ceph.client.admin.keyring
        owner: root
        mode: "0600"
